apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: udagram-feed-api
  labels:
    app: udagram-feed-api
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: udagram-feed-api
    spec:
      restartPolicy: Always
      volumes:
        - name: aws-secret
          secret:
            secretName: aws-secret
      containers:
        - name: udagram-feed-api
          image: ilhancengiz/udagram-feed-api
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 3
            periodSeconds: 3
          volumeMounts:
            - name: aws-secret
              mountPath: "/root/.aws/"
              readOnly: true
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "1024Mi"
              cpu: "500m"
          env:
            - name: URL
              valueFrom:
                configMapKeyRef:
                  name: env-config
                  key: URL
            - name: AWS_BUCKET
              valueFrom:
                secretKeyRef:
                  name: env-secret
                  key: AWS_BUCKET
            - name: AWS_PROFILE
              valueFrom:
                secretKeyRef:
                  name: env-secret
                  key: AWS_PROFILE
            - name: AWS_REGION
              valueFrom:
                secretKeyRef:
                  name: env-secret
                  key: AWS_REGION
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: env-secret
                  key: JWT_SECRET
            - name: POSTGRESS_DB
              valueFrom:
                secretKeyRef:
                  name: env-secret
                  key: POSTGRESS_DB
            - name: POSTGRESS_HOST
              valueFrom:
                secretKeyRef:
                  name: env-secret
                  key: POSTGRESS_HOST
            - name: POSTGRESS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: env-secret
                  key: POSTGRESS_PASSWORD
            - name: POSTGRESS_USERNAME
              valueFrom:
                secretKeyRef:
                  name: env-secret
                  key: POSTGRESS_USERNAME
