apiVersion: apps/v1
kind: Deployment
metadata:
  name: udagram-reverse-proxy
  labels:
    service: udagram-reverse-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      service: udagram-reverse-proxy
  template:
    metadata:
      labels:
        service: udagram-reverse-proxy
    spec:
      restartPolicy: Always
      containers:
        - image: ilhancengiz/udagram-reverse-proxy
          name: udagram-reverse-proxy
          imagePullPolicy: Always
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "1024Mi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 10
          ports:
            - containerPort: 8080
