apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: udagram-frontend
  labels:
    app: udagram-frontend
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: udagram-frontend
        api: external
    spec:
      restartPolicy: Always
      containers:
        - image: ilhancengiz/udagram-frontend
          name: udagram-frontend
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "1024Mi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 3
            periodSeconds: 3
